# TCL File Generated by Component Editor 11.0sp1
# Tue Feb 18 11:45:07 GMT 2014
# DO NOT MODIFY


# +-----------------------------------
# | 
# | counting_matts_top "first_counter" v1.0
# | null 2014.02.18.11:45:07
# | 
# | 
# | /home/netlab/mehall/nios2-ide-workspace-11.0/MattsWork/counting_matts_top.v
# | 
# |    ./counter_bus_mux.v syn, sim
# |    ./counter_bus_mux_bb.v syn, sim
# |    ./counting_matts_top.v syn, sim
# |    ./matt_counter.v syn, sim
# |    ./pll.v syn, sim
# |    ./pll_bb.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module counting_matts_top
# | 
set_module_property NAME counting_matts_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Peripherals/Microcontroller Peripherals"
set_module_property DISPLAY_NAME first_counter
set_module_property TOP_LEVEL_HDL_FILE counting_matts_top.v
set_module_property TOP_LEVEL_HDL_MODULE counting_matts_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME counting_matts_top
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file counter_bus_mux.v {SYNTHESIS SIMULATION}
add_file counter_bus_mux_bb.v {SYNTHESIS SIMULATION}
add_file counting_matts_top.v {SYNTHESIS SIMULATION}
add_file matt_counter.v {SYNTHESIS SIMULATION}
add_file pll.v {SYNTHESIS SIMULATION}
add_file pll_bb.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink osc_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end button export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_1
# | 
add_interface conduit_end_1 conduit end

set_interface_property conduit_end_1 ENABLED true

add_interface_port conduit_end_1 led export Output 4
# | 
# +-----------------------------------
